version: v51
mysql:
  host: ''
  port: ''
  user: ''
  pass: ''
  base: ''
  prefix: betonquest_
language: fr
default_journal_slot: '-1'
max_npc_distance: '5'
journal_colors:
  date:
    day: '9'
    hour: '6'
  line: '4'
  text: '0'
sounds:
  start: ENTITY_VILLAGER_AMBIENT
  end: ENTITY_VILLAGER_YES
  journal: ENTITY_BAT_TAKEOFF
  update: 'false'
  full: 'false'
debug: 'true'
combat_delay: '10'
notify_pullback: 'false'
default_package: default
cmd_blacklist:
- spawn
hook:
  citizens: 'true'
  mythicmobs: 'true'
  vault: 'true'
  worldguard: 'true'
  skript: 'true'
  mcmmo: 'true'
  effectlib: 'true'
  playerpoints: 'true'
  heroes: 'true'
  magic: 'true'
  denizen: 'true'
  skillapi: 'true'
  quests: 'true'
  shopkeepers: 'true'
  placeholderapi: 'true'
  holographicdisplays: 'true'
  racesandclasses: 'true'
  legendquest: 'true'
  worldedit: 'true'
remove_items_after_respawn: 'true'
default_conversation_IO: tellraw
date_format: dd.MM.yyyy HH:mm
conversation_colors:
  npc: dark_green
  text: white,green,italic
  number: yellow
  option: gray
  player: dark_green
  answer: white,gray,italic
journal:
  chars_per_page: '245'
  one_entry_per_page: 'true'
  reversed_order: 'true'
  hide_date: 'true'
  full_main_page: 'true'
effectlib_npc_effect:
  class: VortexEffect
  iterations: 20
  particle: crit_magic
  helixes: 3
  circles: 1
  grow: 0.1
  radius: 0.5
  delay: 5
update:
  enabled: true
  download_bugfixes: true
  notify_new_release: true
  notify_dev_build: true
display_chat_after_conversation: 'true'
quest_items_unbreakable: 'true'
